default_install_hook_types: [pre-commit, pre-push]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files # check added files size
      args: ["--maxkb=500"]
    - id: end-of-file-fixer # fix end of file
      exclude: |
          (?x)
          ^(
            \.sync_state
          )$
    - id: trailing-whitespace # remove trailing whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.2
  hooks:
    - id: ruff-check # lint
    - id: ruff-format # format

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [python]
      pass_filenames: false
      stages: [pre-push]
